# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_authors.Author'),
        ),
    ]
