# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
